export class Genres {
  static Lucas
    : string[] = [
    "pop",
    "r&b",
    "soul",
    "classic rock",
    "glam rock",
    "rock",
    "minimal tech house",
    "art rock",
    "dance rock",
    "mellow gold",
    "new romantic",
    "new wave",
    "new wave pop",
    "pop rock",
    "rock",
    "soft rock",
    "synthpop",
    "chicago indie",
    "chicago rap",
    "conscious hip hop",
    "hip hop",
    "pop rap",
    "rap",
    "disco",
    "funk",
    "post-disco",
    "quiet storm",
    "soul",
    "synth funk",
    "alternative r&b",
    "hip hop",
    "lgbtq+ hip hop",
    "neo soul",
    "pop",
    "chicago soul",
    "classic soul",
    "funk",
    "soul",
    "future garage",
    "house",
    "indie soul",
    "new french touch",
    "nu disco",
    "tropical house",
    "disco",
    "funk",
    "motown",
    "quiet storm",
    "soul",
    "atl hip hop",
    "hip hop",
    "rap",
    "alternative r&b",
    "hip hop",
    "lgbtq+ hip hop",
    "neo soul",
    "pop",
    "classic rock",
    "glam rock",
    "rock",
    "chicago soul",
    "classic soul",
    "funk",
    "soul",
    "pop",
    "r&b",
    "soul",
    "future garage",
    "house",
    "indie soul",
    "new french touch",
    "nu disco",
    "tropical house",
    "disco",
    "funk",
    "post-disco",
    "quiet storm",
    "soul",
    "synth funk",
    "minimal tech house",
    "chicago rap",
    "conscious hip hop",
    "hip hop",
    "pop rap",
    "rap",
    "chicago indie",
    "disco",
    "funk",
    "motown",
    "quiet storm",
    "soul",
    "art rock",
    "dance rock",
    "mellow gold",
    "new romantic",
    "new wave",
    "new wave pop",
    "pop rock",
    "rock",
    "soft rock",
    "synthpop",
    "atl hip hop",
    "hip hop",
    "rap"
  ]

 static Hopper

    : string[] = [
    "arkansas country",
    "outlaw country",
    "arkansas country",
    "outlaw country",
    "indie folk",
    "modern blues rock",
    "new americana",
    "rock",
    "stomp and holler",
    "album rock",
    "british invasion",
    "classic rock",
    "rock",
    "la indie",
    "classic rock",
    "heartland rock",
    "mellow gold",
    "permanent wave",
    "rock",
    "singer-songwriter",
    "album rock",
    "classic rock",
    "country rock",
    "folk",
    "folk rock",
    "mellow gold",
    "rock",
    "singer-songwriter",
    "soft rock",
    "modern alternative rock",
    "modern rock",
    "pop",
    "pop rap",
    "pop rock",
    "rock",
    "stomp pop",
    "classic rock",
    "country rock",
    "folk",
    "folk rock",
    "indie r&b",
    "rock",
    "roots rock",
    "singer-songwriter",
    "alabama indie",
    "album rock",
    "blues rock",
    "classic rock",
    "country rock",
    "double drumming",
    "electric blues",
    "folk rock",
    "hard rock",
    "jam band",
    "mellow gold",
    "rock",
    "roots rock",
    "soft rock",
    "southern rock",
    "la indie",
    "album rock",
    "british invasion",
    "classic rock",
    "rock",
    "indie folk",
    "modern blues rock",
    "new americana",
    "rock",
    "stomp and holler",
    "classic rock",
    "heartland rock",
    "mellow gold",
    "permanent wave",
    "rock",
    "singer-songwriter",
    "classic rock",
    "country rock",
    "folk",
    "folk rock",
    "indie r&b",
    "rock",
    "roots rock",
    "singer-songwriter",
    "alabama indie",
    "album rock",
    "blues rock",
    "classic rock",
    "country rock",
    "double drumming",
    "electric blues",
    "folk rock",
    "hard rock",
    "jam band",
    "mellow gold",
    "rock",
    "roots rock",
    "soft rock",
    "southern rock",
    "modern alternative rock",
    "modern rock",
    "pop",
    "pop rap",
    "pop rock",
    "rock",
    "stomp pop",
    "album rock",
    "classic rock",
    "country rock",
    "folk",
    "folk rock",
    "mellow gold",
    "rock",
    "singer-songwriter",
    "soft rock"
  ]

 static Dustin

    : string[] = [
    "album rock",
    "classic rock",
    "hard rock",
    "mellow gold",
    "rock",
    "soft rock",
    "dance rock",
    "new romantic",
    "new wave",
    "new wave pop",
    "synthpop",
    "zolo",
    "art punk",
    "art rock",
    "dance rock",
    "funk rock",
    "new wave",
    "permanent wave",
    "post-punk",
    "rock",
    "zolo",
    "art punk",
    "art rock",
    "dance rock",
    "funk rock",
    "new wave",
    "permanent wave",
    "post-punk",
    "rock",
    "zolo",
    "rock keyboard",
    "alternative dance",
    "modern rock",
    "alternative rock",
    "east coast hip hop",
    "golden age hip hop",
    "hip hop",
    "old school hip hop",
    "rap",
    "rap rock",
    "art pop",
    "dance rock",
    "europop",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "synthpop",
    "art pop",
    "brooklyn indie",
    "experimental pop",
    "indie pop",
    "indie rock",
    "alternative rock",
    "art punk",
    "art rock",
    "dance rock",
    "new romantic",
    "new wave",
    "post-punk",
    "punk",
    "rock",
    "synth punk",
    "synthpop",
    "zolo",
    "dance rock",
    "new romantic",
    "new wave",
    "new wave pop",
    "synthpop",
    "zolo",
    "album rock",
    "classic rock",
    "hard rock",
    "mellow gold",
    "rock",
    "soft rock",
    "art punk",
    "art rock",
    "dance rock",
    "funk rock",
    "new wave",
    "permanent wave",
    "post-punk",
    "rock",
    "zolo",
    "rock keyboard",
    "alternative dance",
    "modern rock",
    "alternative rock",
    "east coast hip hop",
    "golden age hip hop",
    "hip hop",
    "old school hip hop",
    "rap",
    "rap rock",
    "art punk",
    "art rock",
    "dance rock",
    "funk rock",
    "new wave",
    "permanent wave",
    "post-punk",
    "rock",
    "zolo",
    "art pop",
    "dance rock",
    "europop",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "synthpop",
    "art pop",
    "brooklyn indie",
    "experimental pop",
    "indie pop",
    "indie rock",
    "alternative rock",
    "art punk",
    "art rock",
    "dance rock",
    "new romantic",
    "new wave",
    "post-punk",
    "punk",
    "rock",
    "synth punk",
    "synthpop",
    "zolo",
    "acid rock",
    "classic rock",
    "psychedelic rock",
    "rock",
    "acid rock",
    "classic rock",
    "psychedelic rock",
    "rock"
  ]

static  Eddie

    : string[] = [
    "alternative rock",
    "art punk",
    "art rock",
    "dance rock",
    "new romantic",
    "new wave",
    "post-punk",
    "punk",
    "rock",
    "synth punk",
    "synthpop",
    "zolo",
    "alternative rock",
    "art punk",
    "art rock",
    "dance rock",
    "new romantic",
    "new wave",
    "post-punk",
    "punk",
    "rock",
    "synth punk",
    "synthpop",
    "zolo",
    "glam metal",
    "rock",
    "alternative metal",
    "funk metal",
    "nu metal",
    "rap metal",
    "rock",
    "album rock",
    "glam metal",
    "hard rock",
    "metal",
    "rock",
    "alternative metal",
    "funk metal",
    "nu metal",
    "rap metal",
    "rock",
    "alternative metal",
    "nu metal",
    "rap metal",
    "rock",
    "alternative metal",
    "groove metal",
    "industrial metal",
    "nu metal",
    "rap metal",
    "rap rock",
    "rock",
    "electro-industrial",
    "industrial",
    "industrial metal",
    "industrial rock",
    "alternative metal",
    "alternative rock",
    "grunge",
    "permanent wave",
    "pop rock",
    "rock",
    "spacegrunge",
    "electro-industrial",
    "industrial",
    "industrial metal",
    "industrial rock",
    "album rock",
    "glam metal",
    "hard rock",
    "metal",
    "rock",
    "alternative metal",
    "nu metal",
    "rap metal",
    "rock",
    "alternative metal",
    "funk metal",
    "nu metal",
    "rap metal",
    "rock",
    "alternative metal",
    "funk metal",
    "nu metal",
    "rap metal",
    "rock",
    "glam metal",
    "rock",
    "alternative metal",
    "groove metal",
    "industrial metal",
    "nu metal",
    "rap metal",
    "rap rock",
    "rock",
    "alternative metal",
    "alternative rock",
    "grunge",
    "permanent wave",
    "pop rock",
    "rock",
    "spacegrunge"
  ]

 static Billy

    : string[] = [
    "alternative rock",
    "east coast hip hop",
    "golden age hip hop",
    "hip hop",
    "old school hip hop",
    "rap",
    "rap rock",
    "album rock",
    "classic rock",
    "hard rock",
    "metal",
    "rock",
    "alternative rock",
    "indie rock",
    "modern alternative rock",
    "modern blues rock",
    "modern rock",
    "piano rock",
    "pop rock",
    "rock",
    "stomp and holler",
    "album rock",
    "british blues",
    "classic rock",
    "glam metal",
    "hard rock",
    "metal",
    "rock",
    "modern rock",
    "rock",
    "alternative rock",
    "east coast hip hop",
    "golden age hip hop",
    "hip hop",
    "old school hip hop",
    "rap",
    "rap rock",
    "album rock",
    "classic rock",
    "hard rock",
    "metal",
    "rock",
    "alternative rock",
    "indie rock",
    "modern alternative rock",
    "modern blues rock",
    "modern rock",
    "piano rock",
    "pop rock",
    "rock",
    "stomp and holler",
    "album rock",
    "british blues",
    "classic rock",
    "glam metal",
    "hard rock",
    "metal",
    "rock",
    "modern rock",
    "rock",
    "album rock",
    "classic rock",
    "hard rock",
    "rock",
    "modern hard rock",
    "modern rock",
    "palm desert scene",
    "modern alternative rock",
    "welsh indie",
    "alternative rock",
    "brighton indie",
    "garage rock",
    "modern alternative rock",
    "modern blues rock",
    "modern hard rock",
    "modern rock",
    "rock",
    "album rock",
    "hard rock",
    "nwobhm",
    "rock",
    "modern hard rock",
    "modern rock",
    "palm desert scene",
    "modern alternative rock",
    "welsh indie",
    "album rock",
    "hard rock",
    "nwobhm",
    "rock",
    "album rock",
    "classic rock",
    "hard rock",
    "rock",
    "alternative rock",
    "brighton indie",
    "garage rock",
    "modern alternative rock",
    "modern blues rock",
    "modern hard rock",
    "modern rock",
    "rock"
  ]

 static Jonathan
    : string[] = [
    "art rock",
    "classic rock",
    "glam rock",
    "permanent wave",
    "rock",
    "art rock",
    "classic rock",
    "glam rock",
    "permanent wave",
    "rock",
    "alternative rock",
    "blues rock",
    "detroit rock",
    "garage rock",
    "modern blues rock",
    "modern rock",
    "permanent wave",
    "punk blues",
    "rock",
    "alternative rock",
    "modern rock",
    "rock",
    "chamber pop",
    "indie pop",
    "indie rock",
    "alternative rock",
    "art rock",
    "indie rock",
    "new wave",
    "noise pop",
    "noise rock",
    "post-punk",
    "rock",
    "dance rock",
    "new romantic",
    "new wave",
    "permanent wave",
    "synthpop",
    "heartland rock",
    "new jersey hardcore",
    "new jersey indie",
    "new jersey punk",
    "skate punk",
    "alternative rock",
    "art rock",
    "dream pop",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "pop rock",
    "post-punk",
    "punk",
    "rock",
    "alternative rock",
    "art rock",
    "melancholia",
    "oxford indie",
    "permanent wave",
    "rock",
    "dark rock",
    "dark wave",
    "ethereal wave",
    "gothic rock",
    "alternative rock",
    "art rock",
    "melancholia",
    "oxford indie",
    "permanent wave",
    "rock",
    "alternative rock",
    "art rock",
    "indie rock",
    "new wave",
    "noise pop",
    "noise rock",
    "post-punk",
    "rock",
    "alternative rock",
    "blues rock",
    "detroit rock",
    "garage rock",
    "modern blues rock",
    "modern rock",
    "permanent wave",
    "punk blues",
    "rock",
    "alternative rock",
    "modern rock",
    "rock",
    "chamber pop",
    "indie pop",
    "indie rock",
    "dance rock",
    "new romantic",
    "new wave",
    "permanent wave",
    "synthpop",
    "alternative rock",
    "art rock",
    "dream pop",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "pop rock",
    "post-punk",
    "punk",
    "rock",
    "dark rock",
    "dark wave",
    "ethereal wave",
    "gothic rock",
    "heartland rock",
    "new jersey hardcore",
    "new jersey indie",
    "new jersey punk",
    "skate punk"
  ]

 static Nancy

    : string[] = [
    "adult standards",
    "disco",
    "motown",
    "quiet storm",
    "soft rock",
    "soul",
    "alt z",
    "dance pop",
    "edm",
    "electropop",
    "pop",
    "pop dance",
    "post-teen pop",
    "tropical house",
    "album rock",
    "classic rock",
    "mellow gold",
    "new wave pop",
    "rock",
    "soft rock",
    "dance pop",
    "hollywood",
    "new wave pop",
    "pop",
    "australian hip hop",
    "dance pop",
    "hip pop",
    "pop",
    "pop rap",
    "post-teen pop",
    "dance pop",
    "edm",
    "pop",
    "pop rap",
    "post-teen pop",
    "tropical house",
    "uk pop",
    "disco",
    "hi-nrg",
    "new wave pop",
    "dance pop",
    "girl group",
    "hip pop",
    "pop",
    "r&b",
    "urban contemporary",
    "adult standards",
    "disco",
    "motown",
    "quiet storm",
    "soft rock",
    "soul",
    "alt z",
    "dance pop",
    "edm",
    "electropop",
    "pop",
    "pop dance",
    "post-teen pop",
    "tropical house",
    "album rock",
    "classic rock",
    "mellow gold",
    "new wave pop",
    "rock",
    "soft rock",
    "dance pop",
    "hollywood",
    "new wave pop",
    "pop",
    "australian hip hop",
    "dance pop",
    "hip pop",
    "pop",
    "pop rap",
    "post-teen pop",
    "dance pop",
    "edm",
    "pop",
    "pop rap",
    "post-teen pop",
    "tropical house",
    "uk pop",
    "disco",
    "hi-nrg",
    "new wave pop",
    "dance pop",
    "girl group",
    "hip pop",
    "pop",
    "r&b",
    "urban contemporary",
    "pop",
    "album rock",
    "classic rock",
    "mellow gold",
    "rock",
    "soft rock",
    "yacht rock",
    "dance pop",
    "hip pop",
    "r&b",
    "urban contemporary",
    "pop",
    "dance pop",
    "hip pop",
    "r&b",
    "urban contemporary",
    "album rock",
    "classic rock",
    "mellow gold",
    "rock",
    "soft rock",
    "yacht rock"
  ]

 static Mike

    : string[] = [
    "synthwave",
    "mellow gold",
    "new wave pop",
    "pop rock",
    "soft rock",
    "chillsynth",
    "synthwave",
    "synthwave",
    "mellow gold",
    "new wave pop",
    "pop rock",
    "soft rock",
    "chillsynth",
    "synthwave",
    "new romantic",
    "new wave",
    "new wave pop",
    "synthpop",
    "filter house",
    "popwave",
    "synthwave",
    "hi-nrg",
    "new romantic",
    "new wave",
    "new wave pop",
    "sophisti-pop",
    "synthpop",
    "art rock",
    "new romantic",
    "new wave",
    "new wave pop",
    "steampunk",
    "synthpop",
    "zolo",
    "new romantic",
    "new wave",
    "new wave pop",
    "synthpop",
    "nightrun",
    "popwave",
    "art rock",
    "melancholia",
    "new romantic",
    "new wave",
    "new wave pop",
    "sophisti-pop",
    "art rock",
    "dance rock",
    "mellow gold",
    "new romantic",
    "new wave",
    "new wave pop",
    "rock",
    "soft rock",
    "sophisti-pop",
    "synthpop",
    "filter house",
    "nantes indie",
    "popwave",
    "synthwave",
    "new wave pop",
    "rock keyboard",
    "hi-nrg",
    "new romantic",
    "new wave",
    "new wave pop",
    "sophisti-pop",
    "synthpop",
    "new romantic",
    "new wave",
    "new wave pop",
    "synthpop",
    "filter house",
    "nantes indie",
    "popwave",
    "synthwave",
    "art rock",
    "melancholia",
    "new romantic",
    "new wave",
    "new wave pop",
    "sophisti-pop",
    "nightrun",
    "popwave",
    "art rock",
    "new romantic",
    "new wave",
    "new wave pop",
    "steampunk",
    "synthpop",
    "zolo",
    "new wave pop",
    "rock keyboard",
    "art rock",
    "dance rock",
    "mellow gold",
    "new romantic",
    "new wave",
    "new wave pop",
    "rock",
    "soft rock",
    "sophisti-pop",
    "synthpop",
    "new romantic",
    "new wave",
    "new wave pop",
    "synthpop",
    "filter house",
    "popwave",
    "synthwave"
  ]

 static MrsWheeler

    : string[] = [
    "dance pop",
    "pop",
    "album rock",
    "mellow gold",
    "new romantic",
    "new wave",
    "new wave pop",
    "soft rock",
    "synthpop",
    "art rock",
    "dance rock",
    "mellow gold",
    "new romantic",
    "new wave",
    "new wave pop",
    "rock",
    "scottish new wave",
    "soft rock",
    "synthpop",
    "alternative rock",
    "australian rock",
    "dream pop",
    "new romantic",
    "new wave",
    "pop rock",
    "post-punk",
    "alternative rock",
    "australian rock",
    "dream pop",
    "new romantic",
    "new wave",
    "pop rock",
    "post-punk",
    "hi-nrg",
    "new romantic",
    "new wave",
    "new wave pop",
    "synthpop",
    "album rock",
    "mellow gold",
    "new romantic",
    "new wave",
    "new wave pop",
    "soft rock",
    "synthpop",
    "art rock",
    "dance rock",
    "mellow gold",
    "new romantic",
    "new wave",
    "new wave pop",
    "rock",
    "scottish new wave",
    "soft rock",
    "synthpop",
    "alternative rock",
    "australian rock",
    "dream pop",
    "new romantic",
    "new wave",
    "pop rock",
    "post-punk",
    "alternative rock",
    "australian rock",
    "dream pop",
    "new romantic",
    "new wave",
    "pop rock",
    "post-punk",
    "dance pop",
    "pop",
    "hi-nrg",
    "new romantic",
    "new wave",
    "new wave pop",
    "synthpop",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "rock",
    "sophisti-pop",
    "synthpop",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "soft rock",
    "synthpop",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "soft rock",
    "synthpop",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "rock",
    "sophisti-pop",
    "synthpop",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "soft rock",
    "synthpop",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "soft rock",
    "synthpop"
  ]

 static Murray

    : string[] = [
    "adult standards",
    "lounge",
    "adult standards",
    "harlem renaissance",
    "jazz",
    "jazz blues",
    "lounge",
    "soul",
    "torch song",
    "vocal jazz",
    "adult standards",
    "dixieland",
    "harlem renaissance",
    "jazz trumpet",
    "new orleans jazz",
    "swing",
    "vocal jazz",
    "movie tunes",
    "adult standards",
    "jazz blues",
    "lounge",
    "swing",
    "vocal jazz",
    "adult standards",
    "brill building pop",
    "easy listening",
    "lounge",
    "vocal jazz",
    "adult standards",
    "lounge",
    "swing",
    "vocal harmony group",
    "vocal jazz",
    "adult standards",
    "easy listening",
    "lounge",
    "adult standards",
    "big band",
    "jazz trombone",
    "lounge",
    "stride",
    "swing",
    "vocal jazz",
    "big band",
    "swing",
    "vocal harmony group",
    "adult standards",
    "easy listening",
    "lounge",
    "swing",
    "torch song",
    "vocal jazz",
    "adult standards",
    "cool jazz",
    "jazz",
    "jazz trumpet",
    "lounge",
    "vocal jazz",
    "adult standards",
    "lounge",
    "vocal jazz",
    "adult standards",
    "harlem renaissance",
    "jazz",
    "jazz blues",
    "lounge",
    "soul",
    "torch song",
    "vocal jazz",
    "adult standards",
    "lounge",
    "big band",
    "swing",
    "vocal harmony group",
    "adult standards",
    "dixieland",
    "harlem renaissance",
    "jazz trumpet",
    "new orleans jazz",
    "swing",
    "vocal jazz",
    "adult standards",
    "big band",
    "jazz trombone",
    "lounge",
    "stride",
    "swing",
    "vocal jazz",
    "adult standards",
    "lounge",
    "swing",
    "vocal harmony group",
    "vocal jazz",
    "adult standards",
    "easy listening",
    "lounge",
    "adult standards",
    "brill building pop",
    "easy listening",
    "lounge",
    "vocal jazz",
    "adult standards",
    "jazz blues",
    "lounge",
    "swing",
    "vocal jazz",
    "movie tunes",
    "adult standards",
    "lounge",
    "vocal jazz",
    "adult standards",
    "easy listening",
    "lounge",
    "swing",
    "torch song",
    "vocal jazz",
    "adult standards",
    "cool jazz",
    "jazz",
    "jazz trumpet",
    "lounge",
    "vocal jazz"
  ]

 static Max

    : string[] = [
    "art rock",
    "classic rock",
    "glam rock",
    "permanent wave",
    "rock",
    "alternative metal",
    "permanent wave",
    "punk",
    "rock",
    "skate punk",
    "socal pop punk",
    "new wave",
    "new wave pop",
    "pub rock",
    "punk",
    "scottish new wave",
    "scottish rock",
    "ska",
    "edmonton indie",
    "lo-fi indie",
    "art rock",
    "beatlesque",
    "blues rock",
    "brill building pop",
    "classic rock",
    "cosmic american",
    "country rock",
    "folk",
    "folk rock",
    "mellow gold",
    "psychedelic rock",
    "rock",
    "roots rock",
    "soft rock",
    "british indie rock",
    "art pop",
    "art rock",
    "baroque pop",
    "new wave pop",
    "permanent wave",
    "piano rock",
    "singer-songwriter",
    "alternative metal",
    "permanent wave",
    "punk",
    "rock",
    "skate punk",
    "socal pop punk",
    "new wave",
    "new wave pop",
    "pub rock",
    "punk",
    "scottish new wave",
    "scottish rock",
    "ska",
    "edmonton indie",
    "lo-fi indie",
    "art rock",
    "beatlesque",
    "blues rock",
    "brill building pop",
    "classic rock",
    "cosmic american",
    "country rock",
    "folk",
    "folk rock",
    "mellow gold",
    "psychedelic rock",
    "rock",
    "roots rock",
    "soft rock",
    "british indie rock",
    "art rock",
    "classic rock",
    "glam rock",
    "permanent wave",
    "rock",
    "art pop",
    "art rock",
    "baroque pop",
    "new wave pop",
    "permanent wave",
    "piano rock",
    "singer-songwriter",
    "brill building pop",
    "bubblegum pop",
    "classic rock",
    "folk rock",
    "mellow gold",
    "psychedelic rock",
    "rock",
    "sunshine pop",
    "art pop",
    "chillwave",
    "dreamo",
    "indie pop",
    "indie rock",
    "lo-fi",
    "new jersey indie",
    "noise pop",
    "art pop",
    "chillwave",
    "dreamo",
    "indie pop",
    "indie rock",
    "lo-fi",
    "new jersey indie",
    "noise pop",
    "brill building pop",
    "bubblegum pop",
    "classic rock",
    "folk rock",
    "mellow gold",
    "psychedelic rock",
    "rock",
    "sunshine pop"
  ]


 static Bob
    : string[] = [
    "album rock",
    "classic rock",
    "hard rock",
    "mellow gold",
    "rock",
    "soft rock",
    "europop",
    "classic country pop",
    "country",
    "country dawn",
    "adult standards",
    "classic country pop",
    "country",
    "mellow gold",
    "nashville sound",
    "soft rock",
    "dance pop",
    "pop",
    "post-teen pop",
    "modern alternative rock",
    "chamber ensemble",
    "classical cello",
    "classical performance",
    "rock drums",
    "album rock",
    "classic rock",
    "mellow gold",
    "new wave pop",
    "pop rock",
    "rock",
    "soft rock",
    "rock-and-roll",
    "rockabilly",
    "europop",
    "classic country pop",
    "country",
    "country dawn",
    "adult standards",
    "classic country pop",
    "country",
    "mellow gold",
    "nashville sound",
    "soft rock",
    "dance pop",
    "pop",
    "post-teen pop",
    "modern alternative rock",
    "chamber ensemble",
    "classical cello",
    "classical performance",
    "rock drums",
    "album rock",
    "classic rock",
    "mellow gold",
    "new wave pop",
    "pop rock",
    "rock",
    "soft rock",
    "album rock",
    "classic rock",
    "hard rock",
    "mellow gold",
    "rock",
    "soft rock",
    "rock-and-roll",
    "rockabilly",
    "album rock",
    "art rock",
    "classic rock",
    "mellow gold",
    "new wave",
    "permanent wave",
    "rock",
    "soft rock",
    "glam rock",
    "mellow gold",
    "piano rock",
    "glam rock",
    "mellow gold",
    "piano rock",
    "glam rock",
    "mellow gold",
    "piano rock",
    "europop",
    "new wave pop",
    "soft rock",
    "glam rock",
    "mellow gold",
    "piano rock",
    "album rock",
    "art rock",
    "classic rock",
    "mellow gold",
    "new wave",
    "permanent wave",
    "rock",
    "soft rock",
    "europop",
    "new wave pop",
    "soft rock",
    "glam rock",
    "mellow gold",
    "piano rock",
    "glam rock",
    "mellow gold",
    "piano rock"
  ]

 static Robin

    : string[] = [
    "bedroom pop",
    "indie pop",
    "brooklyn indie",
    "indie pop",
    "brooklyn indie",
    "indie pop",
    "victoria bc indie",
    "europop",
    "swedish pop",
    "bubblegrunge",
    "chicago indie",
    "indie pop",
    "indie pop",
    "candy pop",
    "pixie",
    "pop emo",
    "pop punk",
    "bedroom pop",
    "indie pop",
    "pop",
    "bedroom pop",
    "indie pop",
    "brooklyn indie",
    "indie pop",
    "brooklyn indie",
    "indie pop",
    "victoria bc indie",
    "europop",
    "swedish pop",
    "bubblegrunge",
    "chicago indie",
    "indie pop",
    "indie pop",
    "candy pop",
    "pixie",
    "pop emo",
    "pop punk",
    "bedroom pop",
    "indie pop",
    "pop"
  ]

static  Eleven

    : string[] = [
    "dance pop",
    "pop",
    "dance pop",
    "pop",
    "alternative dance",
    "dance pop",
    "dance-punk",
    "electropop",
    "new rave",
    "art punk",
    "art rock",
    "folk rock",
    "permanent wave",
    "protopunk",
    "rock",
    "art pop",
    "dance pop",
    "electropop",
    "metropopolis",
    "nz pop",
    "pop",
    "acid rock",
    "blues rock",
    "classic rock",
    "folk rock",
    "psychedelic rock",
    "rock",
    "modern blues rock",
    "album rock",
    "jangle pop",
    "mellow gold",
    "new romantic",
    "new wave",
    "new wave pop",
    "paisley underground",
    "pop rock",
    "rock",
    "soft rock",
    "synthpop",
    "album rock",
    "classic rock",
    "hard rock",
    "mellow gold",
    "rock",
    "soft rock",
    "dance pop",
    "pop",
    "alternative dance",
    "dance pop",
    "dance-punk",
    "electropop",
    "new rave",
    "art punk",
    "art rock",
    "folk rock",
    "permanent wave",
    "protopunk",
    "rock",
    "art pop",
    "dance pop",
    "electropop",
    "metropopolis",
    "nz pop",
    "pop",
    "acid rock",
    "blues rock",
    "classic rock",
    "folk rock",
    "psychedelic rock",
    "rock",
    "modern blues rock",
    "album rock",
    "jangle pop",
    "mellow gold",
    "new romantic",
    "new wave",
    "new wave pop",
    "paisley underground",
    "pop rock",
    "rock",
    "soft rock",
    "synthpop",
    "dance pop",
    "pop",
    "album rock",
    "classic rock",
    "hard rock",
    "mellow gold",
    "rock",
    "soft rock",
    "europop",
    "new wave pop",
    "soft rock",
    "europop",
    "new wave pop",
    "soft rock"
  ]

static  Joyce

    : string[] = [
    "gauze pop",
    "indietronica",
    "shiver pop",
    "grand rapids indie",
    "indie pop",
    "michigan indie",
    "grand rapids indie",
    "indie pop",
    "michigan indie",
    "grand rapids indie",
    "indie pop",
    "michigan indie",
    "new wave pop",
    "permanent wave",
    "soft rock",
    "dream smp",
    "indie pop",
    "canadian indie",
    "indie pop",
    "indie rock",
    "shimmer pop",
    "stomp and holler",
    "gauze pop",
    "indietronica",
    "shiver pop",
    "grand rapids indie",
    "indie pop",
    "michigan indie",
    "grand rapids indie",
    "indie pop",
    "michigan indie",
    "new wave pop",
    "permanent wave",
    "soft rock",
    "grand rapids indie",
    "indie pop",
    "michigan indie",
    "dream smp",
    "indie pop",
    "canadian indie",
    "indie pop",
    "indie rock",
    "shimmer pop",
    "stomp and holler",
    "folk-pop",
    "indie folk",
    "indie pop",
    "indiecoustica",
    "san marcos tx indie",
    "shimmer pop",
    "stomp and holler",
    "indie pop",
    "vancouver indie",
    "indie pop",
    "vancouver indie",
    "indie pop",
    "vancouver indie",
    "folk-pop",
    "indie folk",
    "indie pop",
    "indiecoustica",
    "san marcos tx indie",
    "shimmer pop",
    "stomp and holler",
    "indie pop",
    "vancouver indie"
  ]

 static Steve

    : string[] = [
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "rock",
    "sophisti-pop",
    "synthpop",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "soft rock",
    "synthpop",
    "album rock",
    "mellow gold",
    "new wave pop",
    "power pop",
    "soft rock",
    "reggae fusion",
    "album rock",
    "mellow gold",
    "new romantic",
    "new wave",
    "new wave pop",
    "soft rock",
    "synthpop",
    "album rock",
    "classic rock",
    "mellow gold",
    "rock",
    "soft rock",
    "yacht rock",
    "dance pop",
    "pop",
    "art rock",
    "dance rock",
    "hi-nrg",
    "new romantic",
    "new wave",
    "new wave pop",
    "synthpop",
    "canadian pop",
    "pop",
    "mellow gold",
    "rock drums",
    "soft rock",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "soft rock",
    "synthpop",
    "canadian pop",
    "pop",
    "reggae fusion",
    "art rock",
    "dance rock",
    "hi-nrg",
    "new romantic",
    "new wave",
    "new wave pop",
    "synthpop",
    "album rock",
    "classic rock",
    "mellow gold",
    "rock",
    "soft rock",
    "yacht rock",
    "dance pop",
    "pop",
    "mellow gold",
    "rock drums",
    "soft rock",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "rock",
    "sophisti-pop",
    "synthpop",
    "album rock",
    "mellow gold",
    "new romantic",
    "new wave",
    "new wave pop",
    "soft rock",
    "synthpop",
    "album rock",
    "mellow gold",
    "new wave pop",
    "power pop",
    "soft rock"
  ]

static  Will

    : string[] = [
    "new wave",
    "permanent wave",
    "ska",
    "ska revival",
    "alternative rock",
    "garage rock",
    "modern rock",
    "permanent wave",
    "rock",
    "art rock",
    "folk rock",
    "mellow gold",
    "new wave pop",
    "power pop",
    "pub rock",
    "rock",
    "new wave",
    "permanent wave",
    "ska",
    "ska revival",
    "alternative rock",
    "garage rock",
    "modern rock",
    "permanent wave",
    "rock",
    "art rock",
    "folk rock",
    "mellow gold",
    "new wave pop",
    "power pop",
    "pub rock",
    "rock",
    "alternative rock",
    "blues rock",
    "garage rock",
    "indie rock",
    "modern alternative rock",
    "modern blues rock",
    "modern rock",
    "punk blues",
    "rock",
    "supergroup",
    "alabama indie",
    "modern blues rock",
    "rock",
    "classic rock",
    "classic uk pop",
    "folk rock",
    "glam rock",
    "mellow gold",
    "piano rock",
    "classic rock",
    "permanent wave",
    "punk",
    "rock",
    "album rock",
    "art rock",
    "classic rock",
    "mellow gold",
    "new wave",
    "permanent wave",
    "rock",
    "soft rock",
    "art rock",
    "classic rock",
    "glam rock",
    "permanent wave",
    "psychedelic rock",
    "rock",
    "singer-songwriter",
    "classic rock",
    "permanent wave",
    "punk",
    "rock",
    "alabama indie",
    "modern blues rock",
    "rock",
    "classic rock",
    "classic uk pop",
    "folk rock",
    "art rock",
    "classic rock",
    "glam rock",
    "permanent wave",
    "psychedelic rock",
    "rock",
    "singer-songwriter",
    "album rock",
    "art rock",
    "classic rock",
    "mellow gold",
    "new wave",
    "permanent wave",
    "rock",
    "soft rock",
    "glam rock",
    "mellow gold",
    "piano rock",
    "alternative rock",
    "blues rock",
    "garage rock",
    "indie rock",
    "modern alternative rock",
    "modern blues rock",
    "modern rock",
    "punk blues",
    "rock",
    "supergroup"
  ]

 static Argyle

    : string[] = [
    "uk reggae",
    "beatlesque",
    "british invasion",
    "classic rock",
    "merseybeat",
    "psychedelic rock",
    "rock",
    "album rock",
    "art rock",
    "blues rock",
    "classic rock",
    "hard rock",
    "metal",
    "rock",
    "soft rock",
    "acid rock",
    "album rock",
    "blues rock",
    "classic rock",
    "hard rock",
    "proto-metal",
    "psychedelic rock",
    "rock",
    "album rock",
    "classic rock",
    "country rock",
    "folk rock",
    "heartland rock",
    "mellow gold",
    "rock",
    "soft rock",
    "yacht rock",
    "album rock",
    "classic rock",
    "country rock",
    "folk rock",
    "heartland rock",
    "mellow gold",
    "rock",
    "soft rock",
    "yacht rock",
    "art rock",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "post-punk",
    "synthpop",
    "disco",
    "funk rock",
    "reggae",
    "roots reggae",
    "uk reggae",
    "beatlesque",
    "british invasion",
    "classic rock",
    "merseybeat",
    "psychedelic rock",
    "rock",
    "album rock",
    "art rock",
    "blues rock",
    "classic rock",
    "hard rock",
    "metal",
    "rock",
    "soft rock",
    "acid rock",
    "album rock",
    "blues rock",
    "classic rock",
    "hard rock",
    "proto-metal",
    "psychedelic rock",
    "rock",
    "album rock",
    "classic rock",
    "country rock",
    "folk rock",
    "heartland rock",
    "mellow gold",
    "rock",
    "soft rock",
    "yacht rock",
    "art rock",
    "new romantic",
    "new wave",
    "new wave pop",
    "permanent wave",
    "post-punk",
    "synthpop",
    "disco",
    "funk rock",
    "album rock",
    "classic rock",
    "country rock",
    "folk rock",
    "heartland rock",
    "mellow gold",
    "rock",
    "soft rock",
    "yacht rock",
    "reggae",
    "roots reggae",
    "acid rock",
    "classic rock",
    "psychedelic rock",
    "rock",
    "acid rock",
    "classic rock",
    "psychedelic rock",
    "rock"
  ]

}
